[2025-03-20T14:05:35.914+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-20T14:05:35.961+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: store_json_to_postgres.insert_json_to_db manual__2025-03-20T14:05:34.221166+00:00 [queued]>
[2025-03-20T14:05:35.982+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: store_json_to_postgres.insert_json_to_db manual__2025-03-20T14:05:34.221166+00:00 [queued]>
[2025-03-20T14:05:35.983+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 4
[2025-03-20T14:05:36.014+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): insert_json_to_db> on 2025-03-20 14:05:34.221166+00:00
[2025-03-20T14:05:36.027+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=306) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-20T14:05:36.029+0000] {standard_task_runner.py:72} INFO - Started process 307 to run task
[2025-03-20T14:05:36.029+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'store_json_to_postgres', 'insert_json_to_db', 'manual__2025-03-20T14:05:34.221166+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/store_json_to_postgres.py', '--cfg-path', '/tmp/tmp275s5947']
[2025-03-20T14:05:36.036+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask insert_json_to_db
[2025-03-20T14:05:36.093+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-20T14:05:36.155+0000] {task_command.py:467} INFO - Running <TaskInstance: store_json_to_postgres.insert_json_to_db manual__2025-03-20T14:05:34.221166+00:00 [running]> on host 6d922c7b2756
[2025-03-20T14:05:36.328+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='store_json_to_postgres' AIRFLOW_CTX_TASK_ID='insert_json_to_db' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T14:05:34.221166+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-20T14:05:34.221166+00:00'
[2025-03-20T14:05:36.331+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-20T14:05:36.431+0000] {store_json_to_postgres.py:22} INFO - Checking file: /opt/***/Output/Nepal_Profile.json
[2025-03-20T14:05:36.451+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2025-03-20T14:05:38.307+0000] {store_json_to_postgres.py:45} ERROR - Failed: 'contents'
[2025-03-20T14:05:38.462+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/store_json_to_postgres.py", line 37, in insert_json_to_postgres
    (record["title"], record["contents"], json.dumps(record["image_ids"]))
                      ~~~~~~^^^^^^^^^^^^
KeyError: 'contents'
[2025-03-20T14:05:38.564+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=store_json_to_postgres, task_id=insert_json_to_db, run_id=manual__2025-03-20T14:05:34.221166+00:00, execution_date=20250320T140534, start_date=20250320T140535, end_date=20250320T140538
[2025-03-20T14:05:38.635+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-20T14:05:38.637+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 31 for task insert_json_to_db ('contents'; 307)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/store_json_to_postgres.py", line 37, in insert_json_to_postgres
    (record["title"], record["contents"], json.dumps(record["image_ids"]))
                      ~~~~~~^^^^^^^^^^^^
KeyError: 'contents'
[2025-03-20T14:05:38.683+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-20T14:05:38.719+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-20T14:05:38.722+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
